[workspace]
members = [
    "runit"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
description = "EDA toolkit in Rust"
license = "MIT"

[workspace.dependencies]
runit = { path = "./runit", package = "runit", version = "0.1.0" }

serde = "1.0.219"
paste = "1.0"
serde_json = "1.0.141"